/**
 * Serve the canonical JSON Schema at its baked `$id`.
 *
 * The schema's `$id` is `https://adrkit.dev/schema/adr/v<version>/adr.schema.json`
 * (see `schema/adr.schema.json` and `packages/core/src/schema/emit.ts`). For
 * editor `$schema` references and JSON-Schema `$ref` resolution to work, that
 * exact URL must serve the exact bytes of the canonical file.
 *
 * This script is the ONLY thing that puts the schema into the site's served
 * output. It never hand-copies: it reads the single source of truth
 * (`schema/adr.schema.json`, regenerated by `bun run schema:emit` and guarded in
 * CI by `schema-emit-matches`), derives the served path *from the `$id` itself*
 * so a version bump can never silently mismatch, and writes the bytes verbatim
 * under `site/public/`.
 *
 * Run modes:
 *   bun run scripts/sync-schema.ts           # write the served copy (default)
 *   bun run scripts/sync-schema.ts --check    # verify only; exit 1 on drift
 *
 * `--check` is the guard that mirrors `schema-emit-matches`: it asserts the
 * served file exists and is byte-identical to the canonical schema.
 */

import { readFileSync, writeFileSync, mkdirSync } from 'node:fs';
import { dirname, join, resolve } from 'node:path';

const EXPECTED_ORIGIN = 'https://adrkit.dev';

const siteDir = resolve(import.meta.dir, '..');
const repoRoot = resolve(siteDir, '..');
const canonicalPath = join(repoRoot, 'schema', 'adr.schema.json');
const publicDir = join(siteDir, 'public');

export interface ServedSchemaPlan {
  /** Absolute path to the canonical source of truth. */
  canonicalPath: string;
  /** URL pathname derived from the schema `$id`, e.g. `/schema/adr/v0.1.0/adr.schema.json`. */
  servedPathname: string;
  /** Absolute path the schema is served from under `public/`. */
  servedPath: string;
  /** Exact bytes of the canonical schema. */
  bytes: string;
}

/** Read the canonical schema and derive where it must be served from its `$id`. */
export function planServedSchema(): ServedSchemaPlan {
  const bytes = readFileSync(canonicalPath, 'utf8');

  let id: unknown;
  try {
    id = (JSON.parse(bytes) as { $id?: unknown }).$id;
  } catch (error) {
    throw new Error(`Canonical schema is not valid JSON (${canonicalPath}): ${String(error)}`);
  }

  if (typeof id !== 'string' || id.length === 0) {
    throw new Error(`Canonical schema is missing a string "$id" (${canonicalPath})`);
  }

  let url: URL;
  try {
    url = new URL(id);
  } catch {
    throw new Error(`Schema "$id" is not an absolute URL: ${id}`);
  }

  if (url.origin !== EXPECTED_ORIGIN) {
    throw new Error(
      `Schema "$id" origin is "${url.origin}" but this site only serves "${EXPECTED_ORIGIN}". ` +
        `Serving the schema anywhere else would break every editor and $ref pinned to the $id.`,
    );
  }

  // Map the URL pathname (e.g. /schema/adr/v0.1.0/adr.schema.json) into public/.
  const servedPath = join(publicDir, ...url.pathname.split('/').filter(Boolean));

  return { canonicalPath, servedPathname: url.pathname, servedPath, bytes };
}

function rel(path: string): string {
  return path.startsWith(repoRoot) ? path.slice(repoRoot.length + 1) : path;
}

function write(plan: ServedSchemaPlan): void {
  mkdirSync(dirname(plan.servedPath), { recursive: true });
  writeFileSync(plan.servedPath, plan.bytes, 'utf8');

  // Self-check: the bytes we just wrote must read back identical to canonical.
  const written = readFileSync(plan.servedPath, 'utf8');
  if (written !== plan.bytes) {
    throw new Error(`Served schema at ${rel(plan.servedPath)} does not match the canonical bytes`);
  }
}

function check(plan: ServedSchemaPlan): void {
  let served: string;
  try {
    served = readFileSync(plan.servedPath, 'utf8');
  } catch {
    throw new Error(
      `Served schema is missing at ${rel(plan.servedPath)}. Run "bun run sync:schema" to generate it.`,
    );
  }
  if (served !== plan.bytes) {
    throw new Error(
      `Served schema at ${rel(plan.servedPath)} has drifted from ${rel(plan.canonicalPath)}. ` +
        `Regenerate it with "bun run sync:schema".`,
    );
  }
}

function main(): void {
  const checkOnly = process.argv.includes('--check');
  const plan = planServedSchema();

  if (checkOnly) {
    check(plan);
    console.log(`sync-schema: OK — ${rel(plan.servedPath)} matches ${rel(plan.canonicalPath)}`);
    return;
  }

  write(plan);
  console.log(
    `sync-schema: wrote ${rel(plan.servedPath)} (served at ${plan.servedPathname}) ` +
      `from ${rel(plan.canonicalPath)}`,
  );
}

if (import.meta.main) {
  try {
    main();
  } catch (error) {
    console.error(`sync-schema: ${error instanceof Error ? error.message : String(error)}`);
    process.exit(1);
  }
}
