/**
 * Serve the canonical JSON Schema at its baked `$id`.
 *
 * The schema's `$id` is `https://adrkit.dev/schema/adr/v<version>/adr.schema.json`
 * (see `schema/adr.schema.json` and `packages/core/src/schema/emit.ts`). For
 * editor `$schema` references and JSON-Schema `$ref` resolution to work, that
 * exact URL must serve the exact bytes of the canonical file.
 *
 * This script is the ONLY thing that puts the schema into the site's served
 * output. It never hand-copies: it reads the single source of truth
 * (`schema/adr.schema.json`, regenerated by `bun run schema:emit` and guarded in
 * CI by `schema-emit-matches`), derives the served path *from the `$id` itself*
 * so a version bump can never silently mismatch, and writes the bytes verbatim
 * under `site/public/`.
 *
 * Run modes:
 *   bun run scripts/sync-schema.ts           # write the served copy (default)
 *   bun run scripts/sync-schema.ts --check    # verify only; exit 1 on drift
 *
 * `--check` is the guard that mirrors `schema-emit-matches`: it asserts the
 * served file exists and is byte-identical to the canonical schema.
 *
 * ## Retained versions (ADR-0011 action item 6)
 *
 * Every published version path is immutable: a `SCHEMA_VERSION` bump adds a URL
 * and may never remove or repoint one. The canonical file only ever holds the
 * current version, so each previously published schema is committed verbatim
 * under `schema/versions/v<semver>/adr.schema.json` and is never regenerated.
 * This script serves every retained file at the path derived from *its own*
 * `$id`, exactly as it does the canonical one, and `--check` covers all of them.
 * Two further rules make "never repoint" executable: a retained file's `$id`
 * version must equal its directory name, and if the canonical version equals a
 * retained version, their bytes must be identical.
 */

import { readdirSync, readFileSync, writeFileSync, mkdirSync } from 'node:fs';
import { dirname, join, resolve } from 'node:path';

const EXPECTED_ORIGIN = 'https://adrkit.dev';

const siteDir = resolve(import.meta.dir, '..');
const repoRoot = resolve(siteDir, '..');
const canonicalPath = join(repoRoot, 'schema', 'adr.schema.json');
const retainedDir = join(repoRoot, 'schema', 'versions');
const publicDir = join(siteDir, 'public');

export interface ServedSchemaPlan {
  /** Absolute path to the file whose bytes are served (canonical or retained). */
  canonicalPath: string;
  /** The schema `$id` (absolute URL). */
  schemaId: string;
  /** Semantic version parsed from the `$id` path, e.g. `0.1.0`. */
  version: string;
  /** URL pathname derived from the schema `$id`, e.g. `/schema/adr/v0.1.0/adr.schema.json`. */
  servedPathname: string;
  /** Absolute path the schema is served from under `public/`. */
  servedPath: string;
  /** Exact bytes of the canonical schema. */
  bytes: string;
}

/** Read the canonical schema and derive where it must be served from its `$id`. */
export function planServedSchema(): ServedSchemaPlan {
  return planSchemaFile(canonicalPath, publicDir);
}

/** Read one schema file and derive where it must be served from its `$id`. */
export function planSchemaFile(canonicalPath: string, publicDir: string): ServedSchemaPlan {
  const bytes = readFileSync(canonicalPath, 'utf8');

  let id: unknown;
  try {
    id = (JSON.parse(bytes) as { $id?: unknown }).$id;
  } catch (error) {
    throw new Error(`Canonical schema is not valid JSON (${canonicalPath}): ${String(error)}`);
  }

  if (typeof id !== 'string' || id.length === 0) {
    throw new Error(`Canonical schema is missing a string "$id" (${canonicalPath})`);
  }

  let url: URL;
  try {
    url = new URL(id);
  } catch {
    throw new Error(`Schema "$id" is not an absolute URL: ${id}`);
  }

  if (url.origin !== EXPECTED_ORIGIN) {
    throw new Error(
      `Schema "$id" origin is "${url.origin}" but this site only serves "${EXPECTED_ORIGIN}". ` +
        `Serving the schema anywhere else would break every editor and $ref pinned to the $id.`,
    );
  }

  const versionMatch = /\/v(\d+\.\d+\.\d+)\//.exec(url.pathname);
  if (!versionMatch?.[1]) {
    throw new Error(`Schema "$id" path has no v<semver> segment: ${url.pathname}`);
  }

  // Map the URL pathname (e.g. /schema/adr/v0.1.0/adr.schema.json) into public/.
  const servedPath = join(publicDir, ...url.pathname.split('/').filter(Boolean));

  return {
    canonicalPath,
    schemaId: id,
    version: versionMatch[1],
    servedPathname: url.pathname,
    servedPath,
    bytes,
  };
}

const RETAINED_DIR_RE = /^v(\d+\.\d+\.\d+)$/;

/**
 * Plan every retained prior version under `retainedDir`. Each entry must be a
 * `v<semver>` directory holding exactly the `adr.schema.json` that was served at
 * that version, and its `$id` must name the same version as its directory — a
 * mismatch would serve one version's bytes at another version's URL.
 */
export function planRetainedSchemas(retainedDir: string, publicDir: string): ServedSchemaPlan[] {
  let entries: import('node:fs').Dirent[];
  try {
    entries = readdirSync(retainedDir, { withFileTypes: true });
  } catch {
    return [];
  }
  const plans: ServedSchemaPlan[] = [];
  for (const entry of entries.sort((a, b) => (a.name < b.name ? -1 : a.name > b.name ? 1 : 0))) {
    const match = RETAINED_DIR_RE.exec(entry.name);
    if (!entry.isDirectory() || !match?.[1]) {
      throw new Error(
        `Unexpected entry in ${retainedDir}: "${entry.name}". Only v<semver>/ directories belong there.`,
      );
    }
    const plan = planSchemaFile(join(retainedDir, entry.name, 'adr.schema.json'), publicDir);
    if (plan.version !== match[1]) {
      throw new Error(
        `Retained schema ${entry.name}/adr.schema.json declares $id version v${plan.version}; ` +
          `a retained file must be served at the version its directory names.`,
      );
    }
    plans.push(plan);
  }
  return plans;
}

/**
 * The full set of files the site must serve: the canonical schema plus every
 * retained prior version. Throws if the canonical version collides with a
 * retained version whose bytes differ — that would repoint a published URL.
 */
export function planAllServedSchemas(
  options: { canonicalPath: string; retainedDir: string; publicDir: string } = {
    canonicalPath,
    retainedDir,
    publicDir,
  },
): { current: ServedSchemaPlan; retained: ServedSchemaPlan[] } {
  const current = planSchemaFile(options.canonicalPath, options.publicDir);
  const retained = planRetainedSchemas(options.retainedDir, options.publicDir);
  const kept: ServedSchemaPlan[] = [];
  for (const plan of retained) {
    if (plan.version === current.version) {
      if (plan.bytes !== current.bytes) {
        throw new Error(
          `Canonical schema is v${current.version}, and a different v${plan.version} is already ` +
            `retained. A published version path is immutable (ADR-0011): bump SCHEMA_VERSION ` +
            `instead of changing v${plan.version}'s bytes.`,
        );
      }
      continue; // identical: the canonical write already serves it
    }
    kept.push(plan);
  }
  return { current, retained: kept };
}

const metaPath = join(siteDir, 'src', 'generated', 'schema-meta.ts');

/**
 * Emit a generated module so docs pages interpolate the schema URL/version from
 * the single source of truth instead of hardcoding it. A version bump then moves
 * every derived link automatically.
 */
function writeSchemaMeta(plan: ServedSchemaPlan): void {
  const content = `// GENERATED by site/scripts/sync-schema.ts — do not edit.
// Derived from the canonical schema \`$id\` so docs cannot drift from the served
// schema. Regenerated on every dev/build; git-ignored.
export const SCHEMA_ID = ${JSON.stringify(plan.schemaId)} as const;
export const SCHEMA_VERSION = ${JSON.stringify(plan.version)} as const;
export const SCHEMA_PATH = ${JSON.stringify(plan.servedPathname)} as const;
export const SCHEMA_ORIGIN = ${JSON.stringify(EXPECTED_ORIGIN)} as const;
`;
  mkdirSync(dirname(metaPath), { recursive: true });
  writeFileSync(metaPath, content, 'utf8');
}

function rel(path: string): string {
  return path.startsWith(repoRoot) ? path.slice(repoRoot.length + 1) : path;
}

/** Write one plan's bytes to its served path and read them back. */
export function writeServed(plan: ServedSchemaPlan): void {
  mkdirSync(dirname(plan.servedPath), { recursive: true });
  writeFileSync(plan.servedPath, plan.bytes, 'utf8');

  // Self-check: the bytes we just wrote must read back identical to canonical.
  const written = readFileSync(plan.servedPath, 'utf8');
  if (written !== plan.bytes) {
    throw new Error(`Served schema at ${rel(plan.servedPath)} does not match the canonical bytes`);
  }
}

/** Assert one plan's served copy exists and is byte-identical to its source. */
export function checkServed(plan: ServedSchemaPlan): void {
  let served: string;
  try {
    served = readFileSync(plan.servedPath, 'utf8');
  } catch {
    throw new Error(
      `Served schema is missing at ${rel(plan.servedPath)}. Run "bun run sync:schema" to generate it.`,
    );
  }
  if (served !== plan.bytes) {
    throw new Error(
      `Served schema at ${rel(plan.servedPath)} has drifted from ${rel(plan.canonicalPath)}. ` +
        `Regenerate it with "bun run sync:schema".`,
    );
  }
}

// Operational docs that carry live, versioned schema URLs (not ADR prose, which
// is historical). Doc pages under src/content/ derive the version from the
// generated meta module, so they have no literal to go stale.
const VERSION_DOCS = ['DEPLOYMENT.md', 'README.md'];
const SCHEMA_URL_VERSION_RE = /\/schema\/adr\/v(\d+\.\d+\.\d+)\//g;

/**
 * Fail if any operational doc references a schema-URL version that is neither
 * the current one nor a retained prior version. A retained version is still
 * served, so a doc may name it (to say so); an unknown version would 404.
 */
function checkDocVersions(plan: ServedSchemaPlan, retainedVersions: readonly string[]): void {
  const stale: string[] = [];
  for (const doc of VERSION_DOCS) {
    const path = join(siteDir, doc);
    let text: string;
    try {
      text = readFileSync(path, 'utf8');
    } catch {
      continue;
    }
    for (const match of text.matchAll(SCHEMA_URL_VERSION_RE)) {
      if (match[1] !== plan.version && !retainedVersions.includes(match[1] ?? '')) {
        stale.push(`${doc}: found v${match[1]}, expected v${plan.version}`);
      }
    }
  }
  if (stale.length > 0) {
    throw new Error(
      `Stale schema version in docs (canonical is v${plan.version}):\n  ${stale.join('\n  ')}\n` +
        `Update the version-bearing URLs to match the schema $id.`,
    );
  }
}

function main(): void {
  const checkOnly = process.argv.includes('--check');
  const { current: plan, retained } = planAllServedSchemas();
  const all = [plan, ...retained];
  const retainedVersions = retained.map((r) => r.version);

  if (checkOnly) {
    for (const p of all) checkServed(p);
    checkDocVersions(plan, retainedVersions);
    for (const p of all) {
      console.log(`sync-schema: OK — ${rel(p.servedPath)} matches ${rel(p.canonicalPath)}`);
    }
    return;
  }

  for (const p of all) writeServed(p);
  writeSchemaMeta(plan);
  checkDocVersions(plan, retainedVersions);
  for (const p of all) {
    console.log(
      `sync-schema: wrote ${rel(p.servedPath)} (served at ${p.servedPathname}) ` +
        `from ${rel(p.canonicalPath)}`,
    );
  }
}

if (import.meta.main) {
  try {
    main();
  } catch (error) {
    console.error(`sync-schema: ${error instanceof Error ? error.message : String(error)}`);
    process.exit(1);
  }
}
